apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alapaca-prod
  name: alapaca-prod
spec:
  containers:
  - args:
    - ver=1,app=alpaca,env=prod
    image: gcr.io/kuar-demo/kuard-amd64:blue
    name: alapaca-prod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
