apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-rlimit
  name: pod-with-rlimit
spec:
  containers:
  - image: nginx
    name: pod-with-rlimit
    resources: 
     requests:
       cpu: "250m"
       memory: "64Mi"
     limits:
       cpu: "500m"
       memory: "128Mi"
    
    

