apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-v1
  labels:
    release: "stable"
spec: 
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath: 
    path: "/home/waleed/data"
    
    #sdf dfsdfsdfsdf


  
