apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-pod
  name: static-pod
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: static-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
